[package]
name = "open-coroutine-iouring"
version = "0.1.0"
edition = "2021"

[dependencies]
io-uring = "0.6.1"
crossbeam-deque = "0.8.3"
libc = "0.2.147"
cfg-if = "1.0.0"
once_cell = "1.18.0"

[build-dependencies]
cfg-if = "1.0.0"
cc = "1.0.82"

[dev-dependencies]
anyhow = "1.0.75"
slab = "0.4.8"
